# WarWall.gd
# Reactive monitoring wall that changes color based on SOC load
extends MeshInstance3D

@export var pulse_speed: float = 1.5
@export var min_energy: float = 1.0
@export var max_energy: float = 2.5

var time: float = 0.0
var target_color: Color = Color.CYAN
var is_crisis_active: bool = false
var crisis_flicker: float = 0.0

func _ready():
	# Connect to EventBus signals to update color
	EventBus.ticket_added.connect(_update_status)
	EventBus.ticket_completed.connect(func(_t, _type, _time): _update_status())
	EventBus.ticket_timeout.connect(func(_id): _update_status())
	EventBus.world_event_triggered.connect(_on_world_event)
	
	# Initial check
	_update_status()

func _on_world_event(event_id: String, active: bool, _duration: float):
	if event_id in [GlobalConstants.EVENTS.DDOS_ATTACK, GlobalConstants.EVENTS.CRYPTO_SPIKE, GlobalConstants.EVENTS.ZERO_DAY]:
		is_crisis_active = active
		if active:
			target_color = Color.ORANGE if event_id == GlobalConstants.EVENTS.ZERO_DAY else Color.RED
		else:
			_update_status()

func _update_status(_trash = null):
	if is_crisis_active: return # Crisis overrides normal load colors
	
	if not TicketManager: return
	
	var count = TicketManager.get_active_tickets().size()
	
	if count <= 1:
		target_color = Color(0.0, 1.0, 1.0) # Nominal (Cyan/Green)
	elif count <= 3:
		target_color = Color(1.0, 0.8, 0.0) # Warning (Yellow)
	else:
		target_color = Color(1.0, 0.2, 0.1) # Critical (Red)

func _process(delta):
	time += delta * pulse_speed
	
	# Handle Crisis Flicker
	var flicker_mod = 1.0
	if is_crisis_active:
		crisis_flicker += delta * 15.0
		if randf() < 0.3:
			flicker_mod = randf_range(0.2, 1.5)
	
	var energy = lerp(min_energy, max_energy, (sin(time) + 1.0) / 2.0) * flicker_mod
	
	var mat = get_active_material(0)
	if mat is StandardMaterial3D:
		# Smoothly lerp the color for a high-tech transition
		mat.albedo_color = mat.albedo_color.lerp(target_color * 0.5, delta * 2.0)
		mat.emission = mat.emission.lerp(target_color, delta * 2.0)
		mat.emission_energy_multiplier = energy
	
	# Sync other monitors in the office pattern
	if is_crisis_active or flicker_mod != 1.0:
		_sync_office_monitors(target_color, energy)

func _sync_office_monitors(color: Color, energy: float):
	# Pattern match for monitors generated by PropSpawner
	# This is a bit heavy for _process, so we should ideally cache these,
	# but for Phase 5 "Safe" implementation, we'll do it carefully.
	var scene_root = get_tree().current_scene
	if not scene_root: return
	
	# We'll look for "Monitor" in node names or specific groups
	for node in get_tree().get_nodes_in_group("office_monitors"):
		if node is MeshInstance3D:
			var m = node.get_active_material(0)
			if m is StandardMaterial3D:
				m.emission_enabled = true
				m.emission = color
				m.emission_energy_multiplier = energy
